name: workflow-test

on:
  workflow_dispatch:

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
    - name: conan test
      run: conan --version

  test-windows:
    runs-on: windows-latest
    steps:
    - name: conan test
      run: conan --version

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: conan test
      run: conan --version
