name: workflow-test

on:
  workflow_dispatch:

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
    - name: conan test
      run: python -m pip install 'conan==1.60.0'

  test-windows:
    runs-on: windows-latest
    steps:
    - name: conan test
      run: py -m pip install 'conan==1.60.0'

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: conan test
      run: python -m pip install 'conan==1.60.0'
