name: workflow-test

on:
  workflow_dispatch:

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.60.0
    - name: conan version
      run: conan --version

  test-windows:
    runs-on: windows-latest
    steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.60.0
    - name: conan version
      run: conan --version

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.60.0
    - name: conan version
      run: conan --version
